### ISSUE TITLE
Attempt to invoke virtual method 'void com.facebook.UiLifecycleHelper.onPause()' on a null object reference

### ISSUE THREAD

**Issue by skypanther** [mokesmokes/titanium-android-facebook#8]
Suggestions on what I'm doing wrong? I'm getting the following error using module version 3.2.05 and your 3.4.2 SDK build. The sharing dialog briefly appears, then closes. After the error below, I get another for the onResume() activity.

``` shell
[DEBUG] FacebookProxy: (main) [5895,38996] Facebook proxy onPause
[ERROR] TiBaseActivity: (main) [1,38997] Error dispatching lifecycle event: Attempt to invoke virtual method 'void com.facebook.UiLifecycleHelper.onPause()' on a null object reference
[ERROR] TiBaseActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.UiLifecycleHelper.onPause()' on a null object reference
[ERROR] TiBaseActivity:     at com.ti.facebook.ActivityWorkerProxy.onPause(ActivityWorkerProxy.java:83)
```

Here's my relevant code:

``` javascript
var fb = require('com.ti.facebook');
win.fbProxy = fb.createActivityWorker({lifecycleContainer: win});
fb.permissions = ['public_profile'];
if(fb.canPresentShareDialog) {
    fb.share({
        url: 'http://example.com/', 
        namespaceObject: 'myAppnameSpace:graphObject', 
        objectName: 'graphObject', 
        imageUrl: 'http://example.com/image.jpg', 
        title: 'MyApp', 
        description: message, 
        namespaceAction: 'myAppnameSpace:actionType'
    });
} else {
    alert('Unable to share to Facebook. Do you have the Facebook app installed?');
}
```

`win` is a reference to my window, which I've confirmed with 

``` javascript
console.log('<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>')
console.log(win.apiName)
console.log('<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>')
```

which outputs:

``` shell
[INFO]  <<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>
[INFO]  Ti.UI.Window
[INFO]  <<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>
```

I have added the following to my tiapp.xml:

``` xml
<activity android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="MyAppName"/>
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/app_id"/>
```

Android 4.4.4, Galaxy S5, Facebook app v24.0.0.30.15

**Comment by sphairo** [comment]
@mokesmokes 
After you login you never enters .addEventListener('login', function(e) {
        Ti.API.info("ejecutando....");
        if (e.success) {
            alert('login from uid: ' + e.uid + ', name: ' + JSON.parse(e.data).name);
        } else if (e.cancelled) {
            alert('cancelled');
        } else {
            alert(e.error);
        }
        Ti.API.info("terminando....");
    });

In my console print this :

LibraryLoader: Expected native library version number "",actual native library version number ""
[INFO] :   chromium: [INFO:library_loader_hooks.cc(116)] Chromium logging enabled: level = 0, default verbosity = 0
[INFO] :   BrowserStartupController: Initializing chromium process, renderers=0
[ERROR] :  AudioManagerAndroid: BLUETOOTH permission is missing!
[WARN] :   chromium: [WARNING:proxy_service.cc(890)] PAC support disabled because there is no system implementation
[WARN] :   IInputConnectionWrapper: endBatchEdit on inactive InputConnection
[INFO] :   chromium: [INFO:CONSOLE(0)] "event.returnValue is deprecated. Please use the standard event.preventDefault() instead.", source:  (0)

**Comment by mokesmokes** [comment]
@sphairo just curious: why are you using this module instead of the new one from Appcelerator? Appcelerator forked my Facebook project and now bases their modules on my code. You should ask for support from them. https://github.com/appcelerator-modules/ti.facebook
